comment:
  header:
  footer:

labels:
  - name: autorebase:opt-in
    labeled:
      pr:
        body: |
          This PR will automatically rebase if target branch is updated before we merge.
        action: opened
    unlabeled:
      pr:
        body: |
          Opt-out of automatic rebase!
        action: opened
