"type: feature": ["feature/*", "feat/*"]
"type: enhancement": ["enhancement/*", "enhance/*", "enh/*"]
"type: fix": ["fix/*", "bugfix/*"]
"type: hotfix": "hotfix/*"
"type: chore": chore/*
"type: documentation": ["doc/*", "docs/*"]
"type: release": ["release/*", "rel/*"]
