"type: feature":
  - "feature/*"
  - "feat/*"
  - "hotfeat/*"
"type: enhancement":
  - "enhancement/*"
  - "enhance/*"
  - "enhan/*"
  - "enh/*"
"type: fix":
  - "fix/*"
  - "fixes/*"
  - "bugfix/*"
  - "bugfixes/*"
"type: hotfix":
  - "hotfix/*"
  - "hotfixes/*"
  - "hot/*"
"type: chore": chore/*
"type: documentation":
  - "doc/*"
  - "docs/*"
  - "documentation/*"
  - "documentations/*"
  - "document/*"
  - "documents/*"
"type: release": ["release/*", "rel/*"]
