feature: ["feature/*", "feat/*"]
enhancement: ["enhancement/*", "enhance/*", "enh/*"]
fix: ["fix/*", "hotfix/*"]
chore: chore/*
documentation: ["doc/*", "docs/*"]
"type: release": ["release/*", "rel/*"]
