name-template: "$RELEASE_NAME"
categories:
  - title: "🚀 Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
      - "hotfix"
  - title: "🧰 Maintenance"
    labels:
      - "chore"
      - "documentation"

change-template: "- $TITLE (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
references:
  - release/\d+
template: |
  ## Changes

  $CHANGES

autolabeler:
  - label: "documentation"
    branch:
      - '/docs\/.+/'
      - '/doc\/.+/'
  - label: "bug"
    branch:
      - '/fix\/.+/'
      - '/hotfix\/.+/'
  - label: "feature"
    branch:
      - '/feature\/.+/'
      - '/feat\/.+/'
  - label: "enhancement"
    branch:
      - '/enhance\/.+/'
      - '/enhancement\/.+/'
      - '/enh\/.+/'
