name: Automatic Rebase
on:
  issue_comment:
    types: [created]
jobs:
  rebase:
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/rebase')
    name: Rebase
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.KILLIAN_ID }}
          private_key: ${{ secrets.KILLIAN_PRIVATE_KEY }}
      - name: Checkout the latest code
        uses: actions/checkout@v2
        with:
          token: ${{ steps.generate_token.outputs.token }}
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
      - name: Automatic Rebase
        uses: cirrus-actions/rebase@1.4
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
