name: On PR Creation

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events
  pull_request:
    branches: [release/*]
    types: [opened, reopened]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Job "enable-auto-merge"
  enable-automations:
    name: Enbable Automations
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Enable Pull Request Automerge
        uses: alexwilson/enable-github-automerge-action@1.0.0
        with:
          github-token: "${{ secrets.ALFIE_PAT }}"
          merge-method: "REBASE"
      - name: Enable Auto Rebase
        uses: christianvuerings/add-labels@v1
        with:
          labels: |
            autorebase:opt-in
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
