name: Labels Check
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
jobs:
  ready-to-merge:
    name: Ready to Merge
    runs-on: ubuntu-latest
    steps:
      - uses: danielchabr/pr-labels-checker@v3.0
        id: checkLabel
        with:
          hasAll: "status: ready to merge"
          githubToken: ${{ secrets.GITHUB_TOKEN }}
