name: Labels Check
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
jobs:
  default-check:
    name: Default Check
    runs-on: ubuntu-latest
    steps:
      - uses: danielchabr/pr-labels-checker@v3.0
        id: checkLabel
        with:
          hasSome: "Ready to Merge"
          githubToken: ${{ secrets.GITHUB_TOKEN }}
