name: Check Labels
on:
  # Triggers the workflow when pull requests is labeled or unlabeled
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
jobs:
  ready-to-merge:
    name: Ready to Merge
    runs-on: ubuntu-latest
    steps:
      # Check if label 'status: ready to merge' is applied
      - uses: danielchabr/pr-labels-checker@v3.0
        with:
          hasAll: "status: ready to merge"
          githubToken: ${{ secrets.GITHUB_TOKEN }}
