name: Check Labels

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events
  pull_request:
    types: [labeled, unlabeled]
jobs:
  verify-label:
    name: Check Labels
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: jesusvasquez333/verify-pr-label-action@v1.4.0
        if: "${{ github.event.pull_request.state }} != closed"
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          valid-labels: "Ready to Merge"
          invalid-labels: "help wanted, invalid"
      - name: checkout
        uses: actions/checkout@v2
      - name: Label Commenter
        uses: peaceiris/actions-label-commenter@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
