name: On PR Creation

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events
  pull_request:
    types: [opened, reopened]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Job "enable-auto-merge"
  enable-automations:
    name: Enbable Automations
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Enable Pull Request Automerge
        if: ${{ github.event.pull_request.base.ref != 'main' }}
        uses: peter-evans/enable-pull-request-automerge@v1
        with:
          token: ${{ secrets.ALFIE_PAT }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: "REBASE"
      - name: Instructions to Automerge & Rebase
        if: ${{ github.event.pull_request.base.ref != 'main' }}
        uses: github-actions-up-and-running/pr-comment@v1.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message: |
            - This PR has automerge enabled but will only merge when 1 or more reviews have approved and the label ![`Ready to Merge`](https://img.shields.io/badge/-Ready%20to%20Merge-success) is applied.
            - In case the PR's head branch: `${{ github.event.pull_request.head.ref }}` is not up-to-date with its base: `${{ github.event.pull_request.base.ref }}`, you may trigger an auto-rebase by commenting `/rebase`
      - name: Instructions to Rebase
        if: ${{ github.event.pull_request.base.ref == 'main' }}
        uses: github-actions-up-and-running/pr-comment@v1.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message: |
            - This PR intends to merge to `${{ github.event.pull_request.base.ref }}` hence should be extra protected and not have automerge enabled.
            - This PR may only merge when 1 or more reviews have approved and the label ![`Ready to Merge`](https://img.shields.io/badge/-Ready%20to%20Merge-success) is applied.
            - In case the PR's head branch: `${{ github.event.pull_request.head.ref }}` is not up-to-date with its base: `${{ github.event.pull_request.base.ref }}`, you may trigger an auto-rebase by commenting `/rebase`
      - name: Auto Labeler
        uses: TimonVS/pr-labeler-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Label Misc
        if: ${{ github.event.pull_request.labels[0] == null }} # if no label has been applied
        uses: buildsville/add-remove-label@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          label: misc
          type: add
  release-history:
    if: startsWith(github.event.pull_request.head.ref, 'release/')
    name: Release History
    runs-on: ubuntu-latest
    steps:
      - name: Pull Request Body
        uses: technote-space/pr-commit-body-action@v1
