name: On PR Creation

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events
  pull_request:
    types: [opened, reopened]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Job "enable-auto-merge"
  enable-automations:
    if: ${{ github.event.pull_request.base.ref != 'main' }}
    name: Enbable Automations
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Enable Pull Request Automerge
        uses: alexwilson/enable-github-automerge-action@1.0.0
        with:
          github-token: "${{ secrets.ALFIE_PAT }}"
          merge-method: "REBASE"
      - name: Instructions to Automerge
        if: success()
        uses: github-actions-up-and-running/pr-comment@v1.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message: |
            This PR has automerge enabled but will only merge when there are 2 or more reviews have approved and the label ![`Ready to Merge`](https://img.shields.io/badge/-Ready%20to%20Merge-success) is applied.

            In case the PR's `branch: ${{ github.event.pull_request.head.ref }}` is not up-to-date with its `base: ${{ github.event.pull_request.base.ref }}`, you may trigger an auto-rebase by commenting `/rebase`
