# This is a basic workflow to help you get started with Actions

name: GH Context
# change this to the event type you want to get the data for
on:
  issue_comment:
    types: [created]
  pull_request:
    types:
      - "opened"
      - "reopened"
      - "synchronize"
  workflow_dispatch:

jobs:
  printJob:
    name: Print event
    runs-on: ubuntu-latest
    steps:
    - id: checkout_base
      name: "Checkout"
      uses: "actions/checkout@v3"
      with:
        ref: ${{ github.event.pull_request.base.ref }}
    - id: latest_base
      run: |
        echo "sha=$(git rev-parse ${{ github.event.pull_request.base.ref }})" >> $GITHUB_OUTPUT;
    - id: checkout_head
      name: "Checkout"
      uses: "actions/checkout@v3"
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
    - name: Dump PR event
      if: ${{ github.event.pull_request }}
      run: |
        # echo ${{ github.event.pull_request }}
        echo "---"
        echo "${{ steps.latest_base.outputs.sha }}"
        echo "${{ github.event.pull_request.base.sha }}"
