# This is a basic workflow to help you get started with Actions

name: Merge GH Context
# change this to the event type you want to get the data for
on:
  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  printJob:
    # Runs only if merged
    if: github.event.pull_request.merged == true
    name: Print event
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - id: vars
        name: Set variables
        run: |-
          echo "::set-output name=short_sha::$(cut -c 1-7 <<< ${{ github.event.pull_request.head.sha }})"
          echo "::set-output name=branch::$(sed "s/\\//-/g" <<< ${{ github.event.pull_request.head.ref }})"
      - id: print-vars
        name: Print variables
        run: |-
          echo ${{ steps.vars.outputs.short_sha }}
          echo ${{ steps.vars.outputs.branch }}
