# This is a basic workflow to help you get started with Actions

name: Merge GH Context
# change this to the event type you want to get the data for
on:
  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  printJob:
    # Runs only if merged
    if: github.event.pull_request.merged == true
    name: Print event
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
