name: Release Branch Merged

on:
  push:
    branches: [release/*]

jobs:
  # Create PR release/* --> main if DNE
  create-pr-to-default-if-dne:
    name: Create PR to default branch if DNE
    # if: github.event.pull_request.merged == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.RM_ID }}
          private_key: ${{ secrets.RM_PRIVATE_KEY }}
      - name: checkout
        uses: actions/checkout@v2
      - name: Create PR
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main" # If blank, default: master
          pr_title: "Pulling ${{ github.event.push.head.ref }} into main" # Title of pull request
          pr_body: ":crown: *An automated PR*" # Full markdown support, requires pr_title to be set
          github_token: ${{ steps.generate_token.outputs.token }}
