name: Base Action

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events
  pull_request:
    types: [assigned]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Add labels by project
        uses: d-i-bondarenko/project-labeler@v0.2.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
