name: Release Branch Merged

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events
  pull_request:
    branches: [release/*]
    types: [closed]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  create-pr-to-default:
    if: ${{ github.event.pull_request.merged == true }}
    name: Create PR to default branch
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.RM_ID }}
          private_key: ${{ secrets.RM_PRIVATE_KEY }}
      - name: checkout
        uses: actions/checkout@v2
      - name: Create PR
        id: cpr
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ github.event.pull_request.base.ref }}
          destination_branch: "main" # If blank, default: master
          pr_title: "Pulling ${{ github.event.pull_request.base.ref }} into main" # Title of pull request
          pr_body: ":crown: *An automated PR*" # Full markdown support, requires pr_title to be set
          github_token: ${{ steps.generate_token.outputs.token }}
  update-comment:
    name: Update RM Comment
    runs-on: ubuntu-latest
    steps:
      - name: Find Pull Request
        uses: juliangruber/find-pull-request-action@v1
        id: find-pull-request
        with:
          branch: ${{ github.event.pull_request.base.ref }}
      - name: find-comment
        uses: peter-evans/find-comment@v1
        id: fc
        with:
          issue-number: ${{ steps.find-pull-request.outputs.number }}
          comment-author: anthony-masters
      - name: Update comment
        uses: jungwinter/comment@v1
        with:
          type: edit
          body: |
            ${{ steps.find-comment.outputs.comment-body }}
            - [x] ${{ github.event.pull_request.title }} #${{github.event.pull_request.number}}
          comment_id: ${{ steps.find-comment.outputs.comment-id }}
          token: ${{ secrets.GITHUB_TOKEN }}
