name: Release Branch Merged

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events
  pull_request:
    branches: [release/*]
    types: [closed]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  create-pr-to-default:
    name: Create PR to default branch
    if: ${{ github.event.pull_request.merged == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.RM_ID }}
          private_key: ${{ secrets.RM_PRIVATE_KEY }}
      - name: checkout
        uses: actions/checkout@v2
      - name: Create PR
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ github.event.pull_request.base.ref }}
          destination_branch: "main" # If blank, default: master
          pr_title: "Pulling ${{ github.event.pull_request.base.ref }} into main" # Title of pull request
          pr_body: ":crown: *An automated PR*" # Full markdown support, requires pr_title to be set
          pr_label: "autorebase:opt-in"
          github_token: ${{ steps.generate_token.outputs.token }}
