name: Release Branch Merged

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events
  pull_request:
    branches: [release/*]
    types: [closed]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  create-pr-to-default:
    if: ${{ github.event.pull_request.merged == true }}
    name: Create PR to default branch
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.RM_ID }}
          private_key: ${{ secrets.RM_PRIVATE_KEY }}
      - name: checkout
        uses: actions/checkout@v2
      - name: Create PR
        id: cpr
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ github.event.pull_request.base.ref }}
          destination_branch: "main" # If blank, default: master
          pr_title: "Pulling ${{ github.event.pull_request.base.ref }} into main" # Title of pull request
          # Full markdown support, requires pr_title to be set
          pr_body: |
            :crown: *An automated PR*
            <!-- START pr-commits -->
            <!-- END pr-commits -->
          github_token: ${{ steps.generate_token.outputs.token }}
  update-release-draft:
    name: Update Release Draft
    runs-on: ubuntu-latest
    steps:
      - name: Release Drafter
        uses: release-drafter/release-drafter@v5.15.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_NAME: ${{ ${{ github.event.pull_request.base.ref }}
