name: Synchronize Branches

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  auto-rebase:
    name: Auto Rebase
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.KILLIAN_ID }}
          private_key: ${{ secrets.KILLIAN_PRIVATE_KEY }}
      - uses: Label305/AutoRebase@v0.1
        with:
          github_token: ${{ steps.generate_token.outputs.token }}
