on:
  pull_request:
    types: [synchronize]

name: Pull Request updated

jobs:
  release-history:
    if: startsWith(github.event.pull_request.head.ref, 'release/')
    name: Pull Request Body
    runs-on: ubuntu-latest
    steps:
      - name: Pull Request Body
        uses: technote-space/pr-commit-body-action@v1
