name: Triggered by Workflow Run
on:
  # Triggers the workflow when any pull request is synchronized (changes to head)
  workflow_run:
    workflows: [GH Context]
    branches: [main]
    types: [completed]
jobs:
  print:
    # Runs only if event it synchronize
    name: Print more GH Context
    runs-on: ubuntu-latest
    steps:
      # Changes made to head, should be reviewed again
      - name: print
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
